const PORTFOLIO = [
  {
    src: '/assets/imgs/portfolio/carswork.jpg',
    title: 'Cars work',
    popupImageSrc: ['/assets/imgs/portfolio/carsworkhome.jpg'],
    popupSiteLink: 'https://carswork.com',
    popupMissionText: '(Ukraine) - Service ordered by a tow truck. <br/> It is possible to register as a client and register as a tow truck owner. <br/> Our team participated in the development of the backend and partly the frontend.',
  	popupDbs: 'MongoDB',
  	popupDevKnowledge: 'OOP & OOD / TDD & BDD / API (REST API & Postman & Swagger & API Doc)',
  	popupFE: 'Angular (Typescript)',
    popupBE: 'Node.js (Express)',
    urlName: 'carswork',
  },
  {
    src: '/assets/imgs/portfolio/createensemble.PNG',
    title: 'Create Ensemble',
    popupImageSrc: ['/assets/imgs/portfolio/createensemble_home.png'],
    popupSiteLink: 'https://www.createensemble.com/',
    popupMissionText: '(USA) is a social network for creative people. Something like Upwork. <br/> It is possible to register as a user and publish your biography and, as a company, by posting your information, to hire employees for work. <br/> Internal correspondence between me and users, the ability to create groups, add to friends. <br/> The mentoring functionality is also separately implemented, where any registered user can be a mentor or student.',
  	popupDbs: 'PostgreSQL',
  	popupDevKnowledge: 'OOP & OOD / TDD & BDD / API (REST API & Postman & Swagger & API Doc)',
  	popupFE: 'Vue',
  	popupBE: 'Java',
    urlName: 'createensemble',
  },
  {
    src: '/assets/imgs/portfolio/rfs.PNG',
    title: 'Run for Stuff',
    popupImageSrc: ['/assets/imgs/portfolio/rfs_home.PNG'],
    popupSiteLink: 'https://runforstuff.com',
    popupMissionText: 'A hybrid of Groupon and Pokémon Go. The user downloads the application and finds gifts in certain places (discounts from different establishments or stores). <br/> Our team develops a backend and an administrative panel for the application, namely, company registration, payment of discount coupons, mathematical calculations of winning.',
  	popupDbs: 'MongoDB',
  	popupDevKnowledge: 'OOP & OOD / TDD & BDD / API (REST API & Postman & Swagger & API Doc)',
  	popupFE: 'React (Redux Saga)',
  	popupBE: 'Node.js (Loopback TS)',
    urlName: 'rfs',
  },
  {
    src: '/assets/imgs/portfolio/groundworks.PNG',
    title: 'Groundworks',
    popupImageSrc: [
      '/assets/imgs/portfolio/groundworks_home.PNG',
      '/assets/imgs/portfolio/groundworks2_home.PNG',
    ],
    popupMissionText: 'Service for tracking the work of employees. Application and administrative web version.',
  	popupDbs: 'PostgreSQL',
  	popupDevKnowledge: 'OOP & OOD / TDD & BDD / API (REST API & Postman & Swagger & API Doc)',
  	popupFE: 'React (Redux Saga)',
    popupBE: 'Node.js (Nest TS)',
    popupAPP: 'React Native',
    urlName: 'groundworks',
  },
  {
    src: '/assets/imgs/portfolio/social.png',
    title: 'Social Network',
    popupImageSrc: [
      '/assets/imgs/portfolio/social_home.png',
      '/assets/imgs/portfolio/social2_home.png',
    ],
    popupMissionText: 'A new social network for communicating with friends, sharing photos, news, comments. Ability to create chats and groups.',
  	popupDbs: 'PostgreSQL',
  	popupDevKnowledge: 'OOP & OOD / TDD & BDD / API (REST API & Postman & Swagger & API Doc)',
  	popupFE: 'React (Redux Thunk)',
  	popupBE: 'Node.js (Nest TS)',
    urlName: 'socialnetwork',
  },
  {
    src: '/assets/imgs/portfolio/shop.PNG',
    title: 'Shop',
    popupImageSrc: ['/assets/imgs/portfolio/shop_home.PNG'],
    popupMissionText: 'We’ll help you grow and enhance your business using best practices staring from usage of modern technologies and ending with best Agile practices for organizational needs.',
  	popupDbs: 'PostgreSQL',
  	popupDevKnowledge: 'OOP & OOD / TDD & BDD / API (REST API & Postman & Swagger & API Doc)',
  	popupFE: 'NextJS (TS)',
  	popupBE: 'Node.js (Nest TS)',
    urlName: 'shop',
  },
  {
    src: '/assets/imgs/portfolio/connectoro.jpg',
    title: 'Connectoro',
    popupImageSrc: ['/assets/imgs/portfolio/connectoro_home.PNG'],
    popupSiteLink: 'https://app.connectoro.io/login',
    popupMissionText: '(Ireland) development of a backend (admin panel and the backend itself) for a dropshipping company.',
  	popupDbs: 'MongoDB',
  	popupDevKnowledge: 'OOP & OOD / TDD & BDD / API (REST API & Postman & Swagger & API Doc)',
  	popupFE: 'React (Redux Thunk)',
  	popupBE: 'Node.js (Hapi)',
    urlName: 'connectoro',
  },
];

export default PORTFOLIO;
